"""Add memory IOC forensic fields

Revision ID: 5ef5e95986f3
Revises: 447ec366ea25
Create Date: 2026-07-29 15:49:34.362691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef5e95986f3'
down_revision = '447ec366ea25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_iocs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('process_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('offset', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_iocs', schema=None) as batch_op:
        batch_op.drop_column('finding')
        batch_op.drop_column('address')
        batch_op.drop_column('offset')
        batch_op.drop_column('process_name')
        batch_op.drop_column('pid')

    # ### end Alembic commands ###
