"""Add memory analysis tables

Revision ID: 958647339a67
Revises: e0ba40a835f7
Create Date: 2026-07-28 17:21:59.595948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958647339a67'
down_revision = 'e0ba40a835f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_memory_analysis_case_id'), type_='foreignkey')
        batch_op.drop_column('malfind')
        batch_op.drop_column('network')
        batch_op.drop_column('processes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('network', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('malfind', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_memory_analysis_case_id'), 'cases', ['case_id'], ['id'])
        batch_op.drop_column('risk_score')

    # ### end Alembic commands ###
