"""Add evidence processing lifecycle fields

Revision ID: d3fb01d96e25
Revises: 
Create Date: 2026-07-23 15:08:23.476091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fb01d96e25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_old')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('error_message')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')

    op.create_table('evidence_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=500), nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
