"""Upgrade case management fields

Revision ID: e0ba40a835f7
Revises: d2cc080615e2
Create Date: 2026-07-27 17:49:22.844148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ba40a835f7'
down_revision = 'd2cc080615e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('incident_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lead_investigator', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('incident_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_cases_case_number'), ['case_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_case_number'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('closed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('remarks')
        batch_op.drop_column('tags')
        batch_op.drop_column('incident_date')
        batch_op.drop_column('lead_investigator')
        batch_op.drop_column('department')
        batch_op.drop_column('organization')
        batch_op.drop_column('severity')
        batch_op.drop_column('priority')
        batch_op.drop_column('incident_type')
        batch_op.drop_column('case_number')

    # ### end Alembic commands ###
