"""Add memory process fields

Revision ID: ff10e18d93c1
Revises: 5ef5e95986f3
Create Date: 2026-07-30 15:09:37.749739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff10e18d93c1'
down_revision = '5ef5e95986f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exit_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thread_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('handle_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wow64', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('risk_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_memory_processes_pid'), ['pid'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_processes_ppid'), ['ppid'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_processes_process_name'), ['process_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_processes_process_name'))
        batch_op.drop_index(batch_op.f('ix_memory_processes_ppid'))
        batch_op.drop_index(batch_op.f('ix_memory_processes_pid'))
        batch_op.drop_column('risk_reason')
        batch_op.drop_column('session_id')
        batch_op.drop_column('wow64')
        batch_op.drop_column('handle_count')
        batch_op.drop_column('thread_count')
        batch_op.drop_column('exit_time')
        batch_op.drop_column('created_time')
        batch_op.drop_column('parent_name')

    # ### end Alembic commands ###
